version: '3.9'

services:
  api:
    build: ./api
    depends_on:
      - db
    ports:
      - 3010:3000
    environment:
      - DB_HOST=db 
      - DB_USERNAME=root
      - DB_PASSWORD=@@2@22
      - DB_DATABASE=apiafazer
      - DB_PORT=3306
      - WAIT_HOST=db:3306
    volumes:
      - ./api:/api
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=@@2@22
      - MYSQL_DATABASE=apiafazer
    ports:
      - 33060:3306
    volumes:
      - ./database:/var/lib/mysql